"""1.1.28.1 test wave: benchmarks/compare/gen_circuits.py, the brickwork family.

gen_brickwork is the circuit family the MPS bond sweep runs on, added because
the previous family's Schmidt rank peaked at 2 and no swept cap ever bound.
Whether the family SATURATES the caps is a property of the produced state and
is pinned by the C++ suite (V11281BondSaturation) through the simulator. This
file guards the generator itself: the structure it emits, its determinism, the
prefix property that makes a depth sweep a measurement of one family, and the
committed corpus being what the generator produces today.

The module is imported with OUT_DIR redirected to a temporary directory, so no
test can touch the committed corpus.

Repo root resolution: LINDBLAD_REPO_ROOT env var (set by ctest), falling back
to the path of this file (tests/tools/ -> repo root two levels up).
"""

import contextlib
import importlib.util
import io
import math
import os
import re
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(os.environ.get("LINDBLAD_REPO_ROOT",
                                Path(__file__).resolve().parents[2]))
SCRIPT = REPO_ROOT / "benchmarks" / "compare" / "gen_circuits.py"
CORPUS = REPO_ROOT / "benchmarks" / "compare" / "circuits"

CX_RE = re.compile(r"^cx q\[(\d+)\],q\[(\d+)\];$")
U3_RE = re.compile(r"^u3\(([^,]+),([^,]+),([^)]+)\) q\[(\d+)\];$")
QREG_RE = re.compile(r"^qreg q\[(\d+)\];$")


def load_generator(out_dir):
    """Import gen_circuits.py as a fresh module writing into out_dir."""
    spec = importlib.util.spec_from_file_location("gen_circuits", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.OUT_DIR = str(out_dir)
    return mod


def gate_lines(text):
    """The lines after the header: every gate, in order."""
    lines = text.split("\n")
    body = [l for l in lines if not l.startswith("//") and l
            and not l.startswith("OPENQASM") and not l.startswith("include")
            and not l.startswith("qreg")]
    return body


class BrickworkStructure(unittest.TestCase):
    """What one generated file looks like."""

    N = 24
    LAYERS = 8

    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.out = Path(cls.tmp.name)
        cls.gen = load_generator(cls.out)
        cls.gen.gen_brickwork(cls.N, cls.LAYERS, "bw.qasm")
        cls.text = (cls.out / "bw.qasm").read_text()
        cls.body = gate_lines(cls.text)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_header_is_well_formed(self):
        lines = self.text.split("\n")
        self.assertEqual(lines[0], "// brickwork random-SU(4) circuit: %d qubits, %d layers"
                         % (self.N, self.LAYERS))
        self.assertTrue(lines[1].startswith("// generated by"))
        self.assertEqual(lines[2], "OPENQASM 2.0;")
        self.assertEqual(lines[3], 'include "qelib1.inc";')
        m = QREG_RE.match(lines[4])
        self.assertIsNotNone(m)
        self.assertEqual(int(m.group(1)), self.N)
        # Gate-only: the benchmark harness appends its own terminal
        # measurement so both engines sample the identical circuit.
        self.assertNotIn("creg", self.text)
        self.assertNotIn("measure", self.text)
        self.assertTrue(self.text.endswith("\n"))

    def test_only_u3_and_cx_on_valid_wires(self):
        for line in self.body:
            cx = CX_RE.match(line)
            u3 = U3_RE.match(line)
            self.assertTrue(cx or u3, "unexpected line: %r" % line)
            wires = [int(g) for g in (cx.groups() if cx else (u3.group(4),))]
            for w in wires:
                self.assertTrue(0 <= w < self.N, line)
            if u3:
                for angle in u3.groups()[:3]:
                    v = float(angle)
                    self.assertTrue(0.0 <= v < 2.0 * math.pi, line)

    def test_every_cx_is_adjacent_with_the_lower_wire_as_control(self):
        # Adjacent, so the MPS backend inserts no swap chain and every cx is
        # exactly one bond split, which is what the published `lb splits`
        # column counts.
        for line in self.body:
            cx = CX_RE.match(line)
            if cx:
                a, b = int(cx.group(1)), int(cx.group(2))
                self.assertEqual(b, a + 1, line)

    def test_block_pattern_is_the_three_cx_ansatz(self):
        # u3 a, u3 b, then three rounds of (cx a b, u3 a, u3 b). Walk the body
        # block by block; anything else is a malformed block.
        body = list(self.body)
        blocks = 0
        i = 0
        while i < len(body):
            u3a = U3_RE.match(body[i])
            u3b = U3_RE.match(body[i + 1])
            self.assertTrue(u3a and u3b, "block %d does not open with a u3 pair" % blocks)
            a, b = int(u3a.group(4)), int(u3b.group(4))
            self.assertEqual(b, a + 1)
            i += 2
            for _ in range(3):
                cx = CX_RE.match(body[i])
                self.assertTrue(cx, "block %d: expected cx at line %d" % (blocks, i))
                self.assertEqual((int(cx.group(1)), int(cx.group(2))), (a, b))
                ua = U3_RE.match(body[i + 1])
                ub = U3_RE.match(body[i + 2])
                self.assertTrue(ua and ub)
                self.assertEqual((int(ua.group(4)), int(ub.group(4))), (a, b))
                i += 3
            blocks += 1
        even = self.N // 2                 # blocks in an even layer, n even
        odd = (self.N - 1) // 2            # blocks in an odd layer
        expected_blocks = (self.LAYERS // 2) * (even + odd)
        self.assertEqual(blocks, expected_blocks)

    def test_layers_alternate_bond_parity(self):
        # Reconstruct the layer sequence from the first cx of each block: an
        # even layer's blocks start on even wires, an odd layer's on odd
        # wires, and within a layer the starting wires ascend by 2.
        starts = []
        for line in self.body:
            cx = CX_RE.match(line)
            if cx:
                starts.append(int(cx.group(1)))
        # Every block contributes three identical cx; keep one per block.
        starts = starts[::3]
        layer = 0
        expect = 0
        for s in starts:
            if s != expect:
                # A new layer begins: the parity flips and the count restarts.
                layer += 1
                expect = layer % 2
                self.assertEqual(s, expect, "layer %d does not start on wire %d" % (layer, expect))
            expect = s + 2
        self.assertEqual(layer + 1, self.LAYERS)

    def test_cx_count_is_three_per_block(self):
        cx = sum(1 for l in self.body if CX_RE.match(l))
        u3 = sum(1 for l in self.body if U3_RE.match(l))
        self.assertEqual(cx % 3, 0)
        self.assertEqual(u3, 8 * (cx // 3))


class BrickworkDeterminism(unittest.TestCase):
    """Same seed, same file; deeper depth, same prefix."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.out = Path(self.tmp.name)
        self.addCleanup(self.tmp.cleanup)
        self.gen = load_generator(self.out)

    def emit(self, n, layers, name):
        self.gen.gen_brickwork(n, layers, name)
        return (self.out / name).read_text()

    def test_two_generations_are_byte_identical(self):
        a = self.emit(24, 8, "a.qasm")
        b = self.emit(24, 8, "b.qasm")
        self.assertEqual(a, b)

    def test_seed_depends_on_register_size_only(self):
        # The stream is seeded from the register size alone, not the depth, so
        # the gate lines at depth d are a prefix of the gate lines at depth
        # d + 2. The header names the layer count, so the FILES differ at line
        # one; the prefix property is on the body, and that is what makes a
        # depth sweep a measurement of one family rather than unrelated
        # circuits.
        shallow = gate_lines(self.emit(24, 4, "d4.qasm"))
        deeper = gate_lines(self.emit(24, 6, "d6.qasm"))
        deepest = gate_lines(self.emit(24, 8, "d8.qasm"))
        self.assertEqual(deeper[:len(shallow)], shallow)
        self.assertEqual(deepest[:len(deeper)], deeper)
        self.assertLess(len(shallow), len(deeper))
        self.assertLess(len(deeper), len(deepest))

    def test_each_layer_pair_adds_the_same_number_of_blocks(self):
        # On a 24-wire chain a layer pair is 12 even blocks plus 11 odd, each
        # of three cx and eight u3. Derived from the pattern, and checked as
        # the difference between successive depths.
        per_pair_lines = (12 + 11) * (3 + 8)
        d4 = len(gate_lines(self.emit(24, 4, "d4.qasm")))
        d6 = len(gate_lines(self.emit(24, 6, "d6.qasm")))
        d8 = len(gate_lines(self.emit(24, 8, "d8.qasm")))
        self.assertEqual(d6 - d4, per_pair_lines)
        self.assertEqual(d8 - d6, per_pair_lines)

    def test_different_register_sizes_draw_different_streams(self):
        a = gate_lines(self.emit(24, 2, "n24.qasm"))
        b = gate_lines(self.emit(22, 2, "n22.qasm"))
        # The first u3 angle differs, because the seed tag names the width.
        self.assertNotEqual(a[0], b[0])


class CommittedCorpus(unittest.TestCase):
    """The files in the tree are what the generator produces today."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.out = Path(self.tmp.name)
        self.addCleanup(self.tmp.cleanup)
        self.gen = load_generator(self.out)

    def test_brickwork_n24_is_byte_identical_to_a_fresh_generation(self):
        # The published bond sweep runs on this file. A generator edit that
        # changes it silently changes what the sweep measures.
        name = "brickwork_n%d.qasm" % self.gen.BRICKWORK_SIZES[0]
        self.gen.gen_brickwork(self.gen.BRICKWORK_SIZES[0], self.gen.BRICKWORK_LAYERS, name)
        fresh = (self.out / name).read_bytes()
        committed = (CORPUS / name).read_bytes()
        self.assertEqual(fresh, committed)

    def test_brickwork_depth_is_the_measured_value(self):
        # BRICKWORK_LAYERS is measured, not derived: the shallowest depth at
        # which every swept cap discards weight. The saturation itself is
        # pinned in C++; this pins that the committed file was generated at
        # the depth the constant names, so the two cannot drift apart.
        text = (CORPUS / "brickwork_n24.qasm").read_text()
        self.assertIn("%d layers" % self.gen.BRICKWORK_LAYERS, text.split("\n")[0])

    def test_regenerating_the_corpus_changes_nothing(self):
        # gen_brickwork draws from its own seeded stream. Regenerating the
        # whole corpus into a scratch directory must reproduce every committed
        # file, which is the check that adding a family perturbed no other
        # workload's stream.
        with contextlib.redirect_stdout(io.StringIO()):
            self.gen.main()
        produced = sorted(p.name for p in self.out.iterdir())
        committed = sorted(p.name for p in CORPUS.iterdir() if p.is_file())
        self.assertEqual(produced, committed)
        for name in committed:
            self.assertEqual((self.out / name).read_bytes(), (CORPUS / name).read_bytes(),
                             "%s differs from a fresh generation" % name)


if __name__ == "__main__":
    unittest.main()
