// test_eigen_svd_pin.cpp - does the pinned Eigen factorise our two reproducers
// correctly, and does the library path over the same inputs still hold?
//
// Those are two questions, and this file keeps them in two suites, because a
// failure means something different in each and mixing them makes neither
// answerable.
//
//   EigenSvdPin      the DEPENDENCY. Every input is a hex-float literal, so a
//                    failure is attributable to the pinned Eigen and to nothing
//                    else. This is the suite that makes a pin change
//                    self-reporting: bump the pin, run this, read the result.
//
//   LibrarySvdPath   the END-TO-END path. Every input is built by evolving a
//                    circuit through this library, so a failure may belong to
//                    either side. Still worth having, since it is the only
//                    thing that notices when our own construction of these
//                    matrices drifts, but it cannot be read as a verdict on
//                    Eigen.
//
// The distinction is not academic. build_poison_theta() evolves a Shor prefix
// through MPSSimulator and hand-applies the remaining instructions, and
// build_bdcsvd_bug_matrix() evolves a QuditStatevector through a QFT and an
// oracle. Both therefore pass through the code they are meant to be testing,
// and both drift whenever the MPS layer changes. The frozen literals do not.
//
// The other suites over these matrices assert the LADDER's contract: that the
// kept slice is clean and reconstructs, whatever the backend hands it. That is
// the right question for the library and the wrong one for the dependency,
// because the hardening answers it green on a defective Eigen and a healthy one
// alike. Confirmed directly: running three Eigen versions against those suites
// passed 24 of 24 every time, on a version carrying a real defect and on ones
// that do not.
//
// The two reproducers:
//
//   the 36x36, rank 12, twelve-fold degenerate. Eigen 3.4.0's BDCSVD violates
//     the Frobenius identity on it, emitting a singular value belonging to no
//     true spectrum while every entry stays finite. JacobiSVD is correct on the
//     same input. Fixed upstream in 3.4.1.
//
//   the 8x8, spectrum {1,1,1,1,0,0,0,0}. JacobiSVD returns NaN inside a
//     null-space column of U while S, V and the leading rank-4 slice stay exact
//     (issue #44). That failure is a -ffast-math artifact rather than an Eigen
//     defect: the flag folds away the finiteness guard JacobiSVD writes at its
//     own entry, and under strict floating point every Eigen version tested
//     factorises it correctly.
//
// Which is why nothing here carries a per-file floating-point flag. It could
// not deliver one: Eigen's instantiations have vague linkage and the linker
// keeps one per binary regardless of which unit's flags produced it. Strictness
// comes from the factorisation running inside src/eigen_backend.cpp, the tree's
// only emitter, which is compiled strict unconditionally and which
// test_v11241_seam_rules.cpp keeps sole.
//
// The null-space NaN is why these assertions read the FULL factorisation
// through SvdReport::corrupt and the bad-column lists. A kept-slice check
// cannot see it: the damage sits in columns a truncation discards, which is
// exactly why the library survives it and why a pin test must not.

#include <gtest/gtest.h>

#include "diag_r1160_matrices.hpp"
#include "poison_theta_r1151.hpp"
#include "simon36_r1112.hpp"

#include <Eigen/Dense>

#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <set>
#include <vector>

using namespace diag_r1160;
using lindblad::SVDMethod;

namespace {

constexpr double kEps = std::numeric_limits<double>::epsilon();

// Slack a backward-stable SVD is entitled to, in units of N*eps*||M||_F. The
// same figure svd_truncate's VERIFY rung allows, so this suite and the ladder
// agree on what "correct" means and cannot disagree about a given Eigen.
constexpr double kBackwardErrorSlack = 64.0;

double backward_tol(int n, double frob_sq) {
    return kBackwardErrorSlack * static_cast<double>(n) * kEps *
           std::sqrt(frob_sq);
}

// Rank of the Simon residual block, derived rather than transcribed: f is
// constant on the cosets of the subgroup generated by the hidden period, so it
// takes d^n / |<s>| distinct values, and the block carries one direction per
// distinct output.
int simon_distinct_outputs(int d, const std::vector<int>& s) {
    std::set<std::vector<int>> subgroup;
    for (int k = 0; k < d; ++k) {
        std::vector<int> e;
        e.reserve(s.size());
        for (int c : s) e.push_back((k * c) % d);
        subgroup.insert(e);
    }
    int total = 1;
    for (size_t i = 0; i < s.size(); ++i) total *= d;
    return total / static_cast<int>(subgroup.size());
}

// Assert a factorisation is one a correct SVD could have produced. Checks the
// whole of U, S and V, not the retained slice.
void expect_healthy(const char* tag, const SvdReport& r, int n, int expect_rank,
                    double expect_sigma) {
    print_svd_report_line(std::cout, tag, r);

    // Non-finite anywhere in the factorisation, INCLUDING the null-space
    // columns a truncation would discard.
    EXPECT_FALSE(r.s_bad) << tag << ": non-finite singular value";
    EXPECT_TRUE(r.u_bad_cols.empty())
        << tag << ": " << r.u_bad_cols.size() << " column(s) of U hold "
        << "non-finite entries, first at " << r.u_bad_cols.front();
    EXPECT_TRUE(r.v_bad_cols.empty())
        << tag << ": " << r.v_bad_cols.size() << " column(s) of V hold "
        << "non-finite entries, first at " << r.v_bad_cols.front();
    ASSERT_FALSE(r.corrupt) << tag << ": factorisation corrupt, nothing below "
                            << "this point is measurable";

    // Frobenius identity. An SVD preserves the norm exactly, so a violation is
    // a wrong spectrum rather than an imprecise one. This is the check that
    // catches the 36x36 defect, whose output is entirely finite and therefore
    // invisible to every scan above.
    EXPECT_NEAR(r.sum_sq, r.frob_sq, backward_tol(n, r.frob_sq) * r.frob_sq)
        << tag << ": sum of sigma^2 is " << r.sum_sq << " against ||M||_F^2 "
        << r.frob_sq;

    EXPECT_EQ(r.rank, expect_rank) << tag << ": retained rank";

    EXPECT_LT(r.recon_err, backward_tol(n, r.frob_sq))
        << tag << ": U S V^H does not reconstruct M";

    // Every significant sigma sits on the degenerate value. A spurious entry
    // displacing a real one shows up here even when the norm happens to close.
    for (int i = 0; i < expect_rank && i < static_cast<int>(r.top.size()); ++i) {
        EXPECT_NEAR(r.top[static_cast<size_t>(i)], expect_sigma,
                    backward_tol(n, r.frob_sq))
            << tag << ": sigma[" << i << "] is off the degenerate value";
    }
}

// The 36x36 is the residual of a normalised state, so ||M||_F^2 == 1 and the
// rank equal sigmas each carry 1/rank of the weight.
int simon36_rank() { return simon_distinct_outputs(6, {2, 4}); }
double simon36_sigma() {
    return std::sqrt(1.0 / static_cast<double>(simon36_rank()));
}

// The 8x8: four orthonormal directions survive the gate, so the spectrum is
// four ones over a four-dimensional null space and ||M||_F^2 == 4.
constexpr int kPoisonRank = 4;
constexpr double kPoisonSigma = 1.0;

}  // namespace

// =============================================================================
// EigenSvdPin - the dependency, over frozen literals only
// =============================================================================
// Every input below is a hex-float literal that round-trips exactly, so these
// are the only tests in the tree whose failure is attributable to Eigen alone.

TEST(EigenSvdPin, FrozenPoisonThetaJacobiIsCorrect) {
    const auto M = poison_r1151::build_poison_theta_r1151();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 8);
    ASSERT_EQ(M.cols(), 8);

    expect_healthy("pin/jacobi/frozen-poison",
                   run_svd_report(M, SVDMethod::Jacobi), /*n=*/8, kPoisonRank,
                   kPoisonSigma);
}

TEST(EigenSvdPin, FrozenPoisonThetaBdcIsCorrect) {
    const auto M = poison_r1151::build_poison_theta_r1151();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";

    expect_healthy("pin/bdc/frozen-poison", run_svd_report(M, SVDMethod::BDC),
                   /*n=*/8, kPoisonRank, kPoisonSigma);
}

TEST(EigenSvdPin, FrozenSimon36JacobiIsCorrect) {
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    expect_healthy("pin/jacobi/frozen-simon36",
                   run_svd_report(M, SVDMethod::Jacobi), /*n=*/36,
                   simon36_rank(), simon36_sigma());
}

TEST(EigenSvdPin, FrozenSimon36BdcIsCorrect) {
    // The defect this suite exists for. On Eigen 3.4.0 this factorisation
    // returns sum(sigma^2) short of the Frobenius norm with a spurious value
    // displacing a real one, every entry finite. The pinned version does not.
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";

    expect_healthy("pin/bdc/frozen-simon36", run_svd_report(M, SVDMethod::BDC),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(EigenSvdPin, TheFrozenSimon36MatchesItsDocumentedStructure) {
    // A literal is only a reproducer while it is the matrix it claims to be, and
    // nothing else in the tree would notice an editing accident in 1296 hex
    // floats. The structure is stated in the header: real throughout, entries at
    // magnitude 1/6 in a sparse pattern, plus one residue term left by the peel.
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    const double sixth = 1.0 / 6.0;
    int at_sixth = 0;
    double max_imag = 0.0;
    double max_other = 0.0;
    for (Eigen::Index c = 0; c < M.cols(); ++c) {
        for (Eigen::Index r = 0; r < M.rows(); ++r) {
            const double re = std::abs(M(r, c).real());
            max_imag = std::max(max_imag, std::abs(M(r, c).imag()));
            if (std::abs(re - sixth) <= 64.0 * kEps) ++at_sixth;
            else max_other = std::max(max_other, re);
        }
    }

    EXPECT_EQ(max_imag, 0.0)
        << "the frozen matrix is real; a nonzero imaginary part means the "
           "literal was edited or re-emitted from a different state";
    EXPECT_EQ(at_sixth, 3 * simon36_rank())
        << "expected three entries of magnitude 1/6 per retained direction";
    EXPECT_LT(max_other, 1e-15)
        << "every entry that is not 1/6 should be peel residue near zero, but "
           "one reached " << max_other;
    EXPECT_NEAR(M.squaredNorm(), 1.0, backward_tol(36, 1.0))
        << "the block is the residual of a normalised state, so its Frobenius "
           "norm is 1 by construction";
}

// =============================================================================
// LibrarySvdPath - the same questions over inputs this library builds
// =============================================================================
// These inputs are produced by evolving a circuit through Lindblad, so a
// failure here may belong to the library or to Eigen. Kept because they are
// what notices our own construction drifting; read as an end-to-end check and
// never as a verdict on the dependency.

TEST(LibrarySvdPath, BuiltSimon36JacobiIsCorrect) {
    const auto M = build_bdcsvd_bug_matrix();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    expect_healthy("built/jacobi/simon36", run_svd_report(M, SVDMethod::Jacobi),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(LibrarySvdPath, BuiltSimon36BdcIsCorrect) {
    const auto M = build_bdcsvd_bug_matrix();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";

    expect_healthy("built/bdc/simon36", run_svd_report(M, SVDMethod::BDC),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(LibrarySvdPath, BuiltPoisonThetaJacobiIsCorrect) {
    const auto M = build_poison_theta();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 8);
    ASSERT_EQ(M.cols(), 8);

    expect_healthy("built/jacobi/poison", run_svd_report(M, SVDMethod::Jacobi),
                   /*n=*/8, kPoisonRank, kPoisonSigma);
}

TEST(LibrarySvdPath, BuiltPoisonThetaBdcIsCorrect) {
    const auto M = build_poison_theta();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";

    expect_healthy("built/bdc/poison", run_svd_report(M, SVDMethod::BDC),
                   /*n=*/8, kPoisonRank, kPoisonSigma);
}

TEST(LibrarySvdPath, TheBuiltSimon36StillCarriesTheFrozenSpectrum) {
    // What freezing a reproducer buys: the literal cannot drift, so comparing
    // the builder against it says whether OUR construction has moved. The
    // matrices need not agree entry by entry, since the builder's own peel picks
    // an arbitrary basis in each degenerate subspace; the spectrum is the part
    // that is a property of the state rather than of the factorisation.
    const auto built = build_bdcsvd_bug_matrix();
    const auto frozen = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(built));
    ASSERT_EQ(built.rows(), frozen.rows());
    ASSERT_EQ(built.cols(), frozen.cols());

    const auto rb = run_svd_report(built, SVDMethod::Jacobi);
    const auto rf = run_svd_report(frozen, SVDMethod::Jacobi);
    ASSERT_FALSE(rb.corrupt);
    ASSERT_FALSE(rf.corrupt);
    ASSERT_EQ(rb.rank, rf.rank)
        << "the library now builds a block of different rank than the one "
           "frozen from it, so the reproducer has drifted";

    const size_t k = std::min(rb.top.size(), rf.top.size());
    for (size_t i = 0; i < k; ++i) {
        EXPECT_NEAR(rb.top[i], rf.top[i], backward_tol(36, 1.0))
            << "sigma[" << i << "] differs between the built and frozen blocks";
    }
}
