// Copyright (c) 2026 Sricharan Suresh (github.com/verycareful)
// SPDX-License-Identifier: LicenseRef-Lindblad-2.3
//
// This file is part of the Lindblad Quantum Computing Framework and is
// licensed under the Lindblad Software License Agreement, Version 2.3. The
// full text is in the LICENSE file at the root of the repository. Free for
// non-commercial and academic use; commercial use requires a separate
// Commercial License Agreement with the Author.

// test_eigen_svd_pin.cpp - does the pinned Eigen factorise our two reproducers
// correctly, and does the library path over the same inputs still hold?
//
// Those are two questions, and this file keeps them in two suites, because a
// failure means something different in each and mixing them makes neither
// answerable.
//
//   EigenSvdPin      the DEPENDENCY. Every input is a hex-float literal, so a
//                    failure is attributable to the pinned Eigen and to nothing
//                    else. This is the suite that makes a pin change
//                    self-reporting: bump the pin, run this, read the result.
//
//   LibrarySvdPath   the END-TO-END path. Every input is built by evolving a
//                    circuit through this library, so a failure may belong to
//                    either side. Still worth having, since it is the only
//                    thing that notices when our own construction of these
//                    matrices drifts, but it cannot be read as a verdict on
//                    Eigen.
//
// The distinction is not academic. build_poison_theta() evolves a Shor prefix
// through MPSSimulator and hand-applies the remaining instructions, and
// build_bdcsvd_bug_matrix() evolves a QuditStatevector through a QFT and an
// oracle. Both therefore pass through the code they are meant to be testing,
// and both drift whenever the MPS layer changes. The frozen literals do not.
//
// The other suites over these matrices assert the LADDER's contract: that the
// kept slice is clean and reconstructs, whatever the backend hands it. That is
// the right question for the library and the wrong one for the dependency,
// because the hardening answers it green on a defective Eigen and a healthy one
// alike. Confirmed directly: running three Eigen versions against those suites
// passed 24 of 24 every time, on a version carrying a real defect and on ones
// that do not.
//
// The two reproducers:
//
//   the 36x36, rank 12, twelve-fold degenerate. Eigen 3.4.0's BDCSVD violates
//     the Frobenius identity on it, emitting a singular value belonging to no
//     true spectrum while every entry stays finite. JacobiSVD is correct on the
//     same input. Fixed upstream in 3.4.1.
//
//   the 8x8, spectrum {1,1,1,1,0,0,0,0}. JacobiSVD returns NaN inside a
//     null-space column of U while S, V and the leading rank-4 slice stay exact
//     (issue #44). That failure is a -ffast-math artifact rather than an Eigen
//     defect: the flag folds away the finiteness guard JacobiSVD writes at its
//     own entry, and under strict floating point every Eigen version tested
//     factorises it correctly.
//
// Which is why nothing here carries a per-file floating-point flag. It could
// not deliver one: Eigen's instantiations have vague linkage and the linker
// keeps one per binary regardless of which unit's flags produced it. Strictness
// comes from the factorisation running inside src/eigen_backend.cpp, the tree's
// only emitter, which is compiled strict unconditionally and which
// test_v11241_seam_rules.cpp keeps sole.
//
// The null-space NaN is why these assertions read the FULL factorisation
// through SvdReport::corrupt and the bad-column lists. A kept-slice check
// cannot see it: the damage sits in columns a truncation discards, which is
// exactly why the library survives it and why a pin test must not.

#include <gtest/gtest.h>

#include "diag_r1160_matrices.hpp"
#include "poison_theta_r1151.hpp"
#include "simon36_r1112.hpp"

#include "lindblad/simulators/statevector_sim.hpp"
#include "lindblad/statevector.hpp"

#include <Eigen/Dense>

#include <algorithm>
#include <cmath>
#include <complex>
#include <cstddef>
#include <iostream>
#include <limits>
#include <set>
#include <utility>
#include <vector>

using namespace diag_r1160;
using lindblad::SVDMethod;

namespace {

constexpr double kEps = std::numeric_limits<double>::epsilon();

// Slack a backward-stable SVD is entitled to, in units of N*eps*||M||_F. The
// same figure svd_truncate's VERIFY rung allows, so this suite and the ladder
// agree on what "correct" means and cannot disagree about a given Eigen.
constexpr double kBackwardErrorSlack = 64.0;

double backward_tol(int n, double frob_sq) {
    return kBackwardErrorSlack * static_cast<double>(n) * kEps *
           std::sqrt(frob_sq);
}

// Rank of the Simon residual block, derived rather than transcribed: f is
// constant on the cosets of the subgroup generated by the hidden period, so it
// takes d^n / |<s>| distinct values, and the block carries one direction per
// distinct output.
int simon_distinct_outputs(int d, const std::vector<int>& s) {
    std::set<std::vector<int>> subgroup;
    for (int k = 0; k < d; ++k) {
        std::vector<int> e;
        e.reserve(s.size());
        for (int c : s) e.push_back((k * c) % d);
        subgroup.insert(e);
    }
    int total = 1;
    for (size_t i = 0; i < s.size(); ++i) total *= d;
    return total / static_cast<int>(subgroup.size());
}

// Assert a factorisation is one a correct SVD could have produced. Checks the
// whole of U, S and V, not the retained slice.
void expect_healthy(const char* tag, const SvdReport& r, int n, int expect_rank,
                    double expect_sigma) {
    print_svd_report_line(std::cout, tag, r);

    // Non-finite anywhere in the factorisation, INCLUDING the null-space
    // columns a truncation would discard.
    EXPECT_FALSE(r.s_bad) << tag << ": non-finite singular value";
    EXPECT_TRUE(r.u_bad_cols.empty())
        << tag << ": " << r.u_bad_cols.size() << " column(s) of U hold "
        << "non-finite entries, first at " << r.u_bad_cols.front();
    EXPECT_TRUE(r.v_bad_cols.empty())
        << tag << ": " << r.v_bad_cols.size() << " column(s) of V hold "
        << "non-finite entries, first at " << r.v_bad_cols.front();
    ASSERT_FALSE(r.corrupt) << tag << ": factorisation corrupt, nothing below "
                            << "this point is measurable";

    // Frobenius identity. An SVD preserves the norm exactly, so a violation is
    // a wrong spectrum rather than an imprecise one. This is the check that
    // catches the 36x36 defect, whose output is entirely finite and therefore
    // invisible to every scan above.
    EXPECT_NEAR(r.sum_sq, r.frob_sq, backward_tol(n, r.frob_sq) * r.frob_sq)
        << tag << ": sum of sigma^2 is " << r.sum_sq << " against ||M||_F^2 "
        << r.frob_sq;

    EXPECT_EQ(r.rank, expect_rank) << tag << ": retained rank";

    EXPECT_LT(r.recon_err, backward_tol(n, r.frob_sq))
        << tag << ": U S V^H does not reconstruct M";

    // Every significant sigma sits on the degenerate value. A spurious entry
    // displacing a real one shows up here even when the norm happens to close.
    for (int i = 0; i < expect_rank && i < static_cast<int>(r.top.size()); ++i) {
        EXPECT_NEAR(r.top[static_cast<size_t>(i)], expect_sigma,
                    backward_tol(n, r.frob_sq))
            << tag << ": sigma[" << i << "] is off the degenerate value";
    }
}

// The 36x36 is the residual of a normalised state, so ||M||_F^2 == 1 and the
// rank equal sigmas each carry 1/rank of the weight.
int simon36_rank() { return simon_distinct_outputs(6, {2, 4}); }
double simon36_sigma() {
    return std::sqrt(1.0 / static_cast<double>(simon36_rank()));
}

// The 8x8: four orthonormal directions survive the gate, so the spectrum is
// four equal values over a four-dimensional null space. The frozen literal
// holds them at one each, so its ||M||_F^2 == 4.
constexpr int kPoisonRank = 4;
constexpr double kPoisonSigma = 1.0;

// The built block is the canonical block at that point in the run, which
// carries the state's unit norm: the four equal values share a weight of 1,
// so each is 1/sqrt(4).
double built_poison_sigma() {
    return std::sqrt(1.0 / static_cast<double>(kPoisonRank));
}

}  // namespace

// =============================================================================
// EigenSvdPin - the dependency, over frozen literals only
// =============================================================================
// Every input below is a hex-float literal that round-trips exactly, so these
// are the only tests in the tree whose failure is attributable to Eigen alone.

TEST(EigenSvdPin, FrozenPoisonThetaJacobiIsCorrect) {
    const auto M = poison_r1151::build_poison_theta_r1151();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 8);
    ASSERT_EQ(M.cols(), 8);

    expect_healthy("pin/jacobi/frozen-poison",
                   run_svd_report(M, SVDMethod::EigenJacobi), /*n=*/8, kPoisonRank,
                   kPoisonSigma);
}

TEST(EigenSvdPin, FrozenPoisonThetaBdcIsCorrect) {
    const auto M = poison_r1151::build_poison_theta_r1151();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";

    expect_healthy("pin/bdc/frozen-poison", run_svd_report(M, SVDMethod::EigenBDC),
                   /*n=*/8, kPoisonRank, kPoisonSigma);
}

TEST(EigenSvdPin, FrozenSimon36JacobiIsCorrect) {
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    expect_healthy("pin/jacobi/frozen-simon36",
                   run_svd_report(M, SVDMethod::EigenJacobi), /*n=*/36,
                   simon36_rank(), simon36_sigma());
}

TEST(EigenSvdPin, FrozenSimon36BdcIsCorrect) {
    // The defect this suite exists for. On Eigen 3.4.0 this factorisation
    // returns sum(sigma^2) short of the Frobenius norm with a spurious value
    // displacing a real one, every entry finite. The pinned version does not.
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(M)) << "frozen literal corrupt before any SVD ran";

    expect_healthy("pin/bdc/frozen-simon36", run_svd_report(M, SVDMethod::EigenBDC),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(EigenSvdPin, TheFrozenSimon36MatchesItsDocumentedStructure) {
    // A literal is only a reproducer while it is the matrix it claims to be, and
    // nothing else in the tree would notice an editing accident in 1296 hex
    // floats. The structure is stated in the header: real throughout, entries at
    // magnitude 1/6 in a sparse pattern, plus one residue term left by the peel.
    const auto M = simon36_r1112::build_simon36_r1112();
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    const double sixth = 1.0 / 6.0;
    int at_sixth = 0;
    double max_imag = 0.0;
    double max_other = 0.0;
    for (Eigen::Index c = 0; c < M.cols(); ++c) {
        for (Eigen::Index r = 0; r < M.rows(); ++r) {
            const double re = std::abs(M(r, c).real());
            max_imag = std::max(max_imag, std::abs(M(r, c).imag()));
            if (std::abs(re - sixth) <= 64.0 * kEps) ++at_sixth;
            else max_other = std::max(max_other, re);
        }
    }

    EXPECT_EQ(max_imag, 0.0)
        << "the frozen matrix is real; a nonzero imaginary part means the "
           "literal was edited or re-emitted from a different state";
    EXPECT_EQ(at_sixth, 3 * simon36_rank())
        << "expected three entries of magnitude 1/6 per retained direction";
    EXPECT_LT(max_other, 1e-15)
        << "every entry that is not 1/6 should be peel residue near zero, but "
           "one reached " << max_other;
    EXPECT_NEAR(M.squaredNorm(), 1.0, backward_tol(36, 1.0))
        << "the block is the residual of a normalised state, so its Frobenius "
           "norm is 1 by construction";
}

// =============================================================================
// LibrarySvdPath - the same questions over inputs this library builds
// =============================================================================
// These inputs are produced by evolving a circuit through Lindblad, so a
// failure here may belong to the library or to Eigen. Kept because they are
// what notices our own construction drifting; read as an end-to-end check and
// never as a verdict on the dependency.

TEST(LibrarySvdPath, BuiltSimon36JacobiIsCorrect) {
    const auto M = build_bdcsvd_bug_matrix();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 36);
    ASSERT_EQ(M.cols(), 36);

    expect_healthy("built/jacobi/simon36", run_svd_report(M, SVDMethod::EigenJacobi),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(LibrarySvdPath, BuiltSimon36BdcIsCorrect) {
    const auto M = build_bdcsvd_bug_matrix();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";

    expect_healthy("built/bdc/simon36", run_svd_report(M, SVDMethod::EigenBDC),
                   /*n=*/36, simon36_rank(), simon36_sigma());
}

TEST(LibrarySvdPath, BuiltPoisonThetaJacobiIsCorrect) {
    const auto M = build_poison_theta();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";
    ASSERT_EQ(M.rows(), 8);
    ASSERT_EQ(M.cols(), 8);

    expect_healthy("built/jacobi/poison", run_svd_report(M, SVDMethod::EigenJacobi),
                   /*n=*/8, kPoisonRank, built_poison_sigma());
}

TEST(LibrarySvdPath, BuiltPoisonThetaBdcIsCorrect) {
    const auto M = build_poison_theta();
    ASSERT_FALSE(matrix_bad(M)) << "reproducer corrupt before any SVD ran";

    expect_healthy("built/bdc/poison", run_svd_report(M, SVDMethod::EigenBDC),
                   /*n=*/8, kPoisonRank, built_poison_sigma());
}

TEST(LibrarySvdPath, TheBuiltPoisonThetaIsTheCanonicalBlock) {
    // What "the canonical block at that point" promises, checked two ways that
    // do not depend on the SVD the other tests examine.
    //
    // First, the block carries the chain's whole norm. The sites left of 5 are
    // left-orthonormal and those right of 6 right-orthonormal, so they contract
    // to the identity and ||theta||_F^2 is <psi|psi>; the cp core is unitary
    // and leaves it unchanged. A block read in any other gauge carries some
    // other figure (the frozen literal's is 4).
    const lindblad::MPSState chain = build_poison_chain();
    EXPECT_EQ(chain.open_span(), (std::pair<int, int>{6, 6}))
        << "the builder must leave the centre where the library's swap chain "
           "leaves it";
    const auto M = build_poison_theta();
    ASSERT_FALSE(matrix_bad(M));
    const double norm_sq = chain.norm_sq();
    EXPECT_NEAR(M.squaredNorm(), norm_sq, backward_tol(8, norm_sq) * norm_sq)
        << "the block does not carry the chain's norm, so it is not the "
           "canonical block";

    // Second, its spectrum is the state's Schmidt spectrum across the (5 | 6)
    // cut, taken from a dense evolution of the same instructions: the prefix
    // up to instruction 26, then that instruction's swap-down of (6, 7), and
    // then its cp core on (5, 6), written out as the two gates they are.
    const auto qc = poison_circuit();
    lindblad::QuantumCircuit dense_qc(qc.n_qubits);
    dense_qc.instructions.assign(qc.instructions.begin(),
                                 qc.instructions.begin() + kPoisonInstruction);
    dense_qc.swap(6, 7);
    lindblad::Statevector sv(dense_qc.n_qubits);
    sv.initialize_basis(0);
    lindblad::StatevectorSimulator ssim;
    for (const auto& inst : dense_qc.instructions) ssim.apply_instruction(sv, inst);

    // The chain approximates the dense state only as closely as its splits
    // allowed, and that distance is measured here, where both hold the state
    // after the swap-down. For unit vectors at their best relative phase
    // ||a - b||^2 is 2 (1 - |<a|b>|); 4 eps covers the rounding in forming it
    // near 1. The cp core is unitary and acts alike on both, so the distance
    // carries over to the states the spectra below are taken from.
    const lindblad::Statevector mps_sv = chain.to_statevector();
    std::complex<double> ov(0.0, 0.0);
    double dense_sq = 0.0;
    double mps_sq = 0.0;
    for (std::size_t i = 0; i < sv.dim; ++i) {
        const std::complex<double> a(sv.real_parts[i], sv.imag_parts[i]);
        ov += std::conj(a) * std::complex<double>(mps_sv.real_parts[i],
                                                  mps_sv.imag_parts[i]);
        dense_sq += std::norm(a);
        mps_sq += mps_sv.real_parts[i] * mps_sv.real_parts[i] +
                  mps_sv.imag_parts[i] * mps_sv.imag_parts[i];
    }
    ASSERT_GT(dense_sq, 0.0);
    ASSERT_GT(mps_sq, 0.0);
    const double overlap = std::abs(ov) / std::sqrt(dense_sq * mps_sq);
    const double distance =
        std::sqrt(2.0 * std::max(0.0, 1.0 - overlap) + 4.0 * kEps);

    lindblad::QuantumCircuit core(qc.n_qubits);
    core.cp(qc.instructions[kPoisonInstruction].params[0], 5, 6);
    for (const auto& inst : core.instructions) ssim.apply_instruction(sv, inst);

    // Qubit q is bit q of the amplitude index, so qubits 0..5 are the low six
    // bits: the row index of the reshaped state, the rest the column index.
    constexpr int kLeftQubits = 6;
    const int left_dim = 1 << kLeftQubits;
    const int right_dim = static_cast<int>(sv.dim) / left_dim;
    Eigen::MatrixXcd psi(left_dim, right_dim);
    for (std::size_t i = 0; i < sv.dim; ++i) {
        psi(static_cast<Eigen::Index>(i % static_cast<std::size_t>(left_dim)),
            static_cast<Eigen::Index>(i / static_cast<std::size_t>(left_dim))) =
            std::complex<double>(sv.real_parts[i], sv.imag_parts[i]);
    }
    Eigen::VectorXd s_dense, s_block;
    Eigen::MatrixXcd Ud, Vd, Ub, Vb;
    ASSERT_TRUE(seam_svd(psi, SVDMethod::EigenJacobi, s_dense, Ud, Vd));
    ASSERT_TRUE(seam_svd(M, SVDMethod::EigenJacobi, s_block, Ub, Vb));

    // Singular values are 1-Lipschitz in the Frobenius norm (Weyl), and the
    // reshaped difference of two states has the Frobenius norm of the vector
    // difference, so `distance` bounds every sigma difference below. The
    // chain's own norm is divided out of the block, and the backward error of
    // the two factorisations is added on top.
    const double tol = distance + backward_tol(8, 1.0) +
                       backward_tol(left_dim, 1.0);

    const double block_scale = std::sqrt(norm_sq);
    const Eigen::Index k = s_block.size();
    ASSERT_LE(k, s_dense.size());
    for (Eigen::Index i = 0; i < k; ++i) {
        EXPECT_NEAR(s_block(i) / block_scale, s_dense(i) / std::sqrt(dense_sq), tol)
            << "sigma[" << i << "] of the built block is not the state's Schmidt "
               "coefficient across the (5 | 6) cut";
    }
    // Everything the block cannot hold must be absent from the state too, or
    // the block is missing a direction rather than merely being small.
    for (Eigen::Index i = k; i < s_dense.size(); ++i) {
        EXPECT_LT(s_dense(i) / std::sqrt(dense_sq), tol)
            << "the state has weight in Schmidt direction " << i
            << " which an 8x8 block cannot carry";
    }
    for (Eigen::Index i = 0; i < k; ++i) {
        const double expected = (i < kPoisonRank) ? built_poison_sigma() : 0.0;
        EXPECT_NEAR(s_dense(i) / std::sqrt(dense_sq), expected, tol)
            << "the dense Schmidt spectrum is not four equal values, so the "
               "flat-spectrum premise of this reproducer no longer holds";
    }
}

TEST(LibrarySvdPath, TheBuiltSimon36StillCarriesTheFrozenSpectrum) {
    // What freezing a reproducer buys: the literal cannot drift, so comparing
    // the builder against it says whether OUR construction has moved. The
    // matrices need not agree entry by entry, since the builder's own peel picks
    // an arbitrary basis in each degenerate subspace; the spectrum is the part
    // that is a property of the state rather than of the factorisation.
    const auto built = build_bdcsvd_bug_matrix();
    const auto frozen = simon36_r1112::build_simon36_r1112();
    ASSERT_FALSE(matrix_bad(built));
    ASSERT_EQ(built.rows(), frozen.rows());
    ASSERT_EQ(built.cols(), frozen.cols());

    const auto rb = run_svd_report(built, SVDMethod::EigenJacobi);
    const auto rf = run_svd_report(frozen, SVDMethod::EigenJacobi);
    ASSERT_FALSE(rb.corrupt);
    ASSERT_FALSE(rf.corrupt);
    ASSERT_EQ(rb.rank, rf.rank)
        << "the library now builds a block of different rank than the one "
           "frozen from it, so the reproducer has drifted";

    const size_t k = std::min(rb.top.size(), rf.top.size());
    for (size_t i = 0; i < k; ++i) {
        EXPECT_NEAR(rb.top[i], rf.top[i], backward_tol(36, 1.0))
            << "sigma[" << i << "] differs between the built and frozen blocks";
    }
}
